### ISSUE TITLE
is this repo still maintained ? 

### ISSUE THREAD

**Issue by tahayk** [ericmccarthy7/clickhouse-pool#14]
I came across your repository, it looks really interesting and it matches my requirements.
So I'm wondering if it is still maintained ?
Thank you in advance.

**Comment by ericmccarthy7** [comment]
It's currently still working for me and I haven't had any bug reports in years. Thanks to it being dead simple I haven't had to make any changes in a long time.

It does however look like it is being used in https://github.com/PostHog/posthog still. Hopefully that gives you some confidence!

Regarding https://github.com/mymarilyn/clickhouse-driver/issues/371 I would have no problem with anyone from the community merging our work together but I do not have time at the moment to do it myself.
