### ISSUE TITLE
Reasons to not support Python >=3.5 ?

### ISSUE THREAD

**Issue by elhoyos** [ericmccarthy7/clickhouse-pool#7]
From the intro:
> The package requires Python 3.8 and above due to typing.

Thing is that all tests pass for me in 3.5.7 and 3.6.2. Is there any special reason to stick with versions >=3.8?

**Comment by ericmccarthy7** [comment]
It's possible at the time of writing that line I was using newer features of typing, but opted not to use them. At a quick glance I don't see why it couldn't be backwards compatible. 

I can remove the line or if you do some further testing or you can open a PR yourself I'd be happy with that!
